### ISSUE TITLE
debug.log size issue

### ISSUE THREAD

**Issue by davembg** [LIMXTEC/DMDv3#10]
This issue tracker is only for technical issues related to DMD Core.
General DMD questions and/or support requests and are best directed to the [DMD Slack](http://diamond.slack.com).

#### If so, please list the steps to reproduce below:
1. start the application
2. let it run
3. in 24hrs, my debug.log was 109GB

### Expected behavior
log should rotate or null with max-size by default

### Actual behavior
log just grows without fs consideration

### Screenshots.
na

### What version of DMD Core are you using?
OS X build, not debug -

### Machine specs:
- OS: Sierra
- CPU: Xeon 3.5GHz 6-core late 2013 MacPro
- RAM: 16GB
- Disk size: 256GB
- Disk Type (HD/SDD): SSD

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log`, `db.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by joshafest** [comment]
I think I already fixed it .... let me see my commit get lost I think

**Comment by limxdev** [comment]
Frank has written a similar function for bitsend. This can we here use.

**Comment by davembg** [comment]
I can confirm the fix....both OS X and WIN current builds seem to manage the debug.log size nice.
