### ISSUE TITLE
Multisend not working

### ISSUE THREAD

**Issue by donnk** [LIMXTEC/DMDv3#26]
This issue tracker is only for technical issues related to DMD Core.
General DMD questions and/or support requests and are best directed to the [DMD Slack](http://diamond.slack.com).

### Describe the issue
On masternode control wallet, using the UI to setup multisend to another address, the address is shown and shows active but it sends nothing. If the console is used to setup the address it works perfect so maybe another UI issue.

### Can you reliably reproduce the issue?
yes
#### If so, please list the steps to reproduce below:
1. use the ui
2.
3.

### Expected behavior
Tmultisend should work

### Actual behavior
multisend doesnt work.

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of DMD Core are you using?
3.0.0.12

### Machine specs:
- OS: win10
- CPU: i5
- RAM: 8gb
- Disk size: 500
- Disk Type (SDD):

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log`, `db.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by limxdev** [comment]
The Multisend function need 640 conf for working. The wallet have to be 24/7 online (unlocked for staking)

**Comment by donnk** [comment]
yes agree. it had confirms 640 but was not sending. i saw two trans do this and then wiped multisend from console and setup again from console and worked perfect.

**Comment by donnk** [comment]
3.0.0.13 seems to have fixed this. Thanks!
