### ISSUE TITLE
Starting masternode: portmapped client doesn't start properly

### ISSUE THREAD

**Issue by jerpat** [LIMXTEC/DMDv3#38]
### Describe the issue
When attempting to start a valid masternode configuration and wallet (i.e., masternode.conf is set up properly and the account has 10k of DMD)  (e.g., diamond-cli masternode start-alias <alias>), the result of the command reports success:
```
{
    "alias" : "MyMaster",
    "result" : "successful"
}
```
But the status of the masternode comes back as: "Not capable masternode..."
```
{
    "vin" : "CTxIn(COutPoint(0000000000000000000000000000000000000000000000000000000000000000, 4294967295), coinbase )",
    "service" : "\<myip>:17771",
    "status" : "Not capable masternode: Could not connect to \<myip>:17771"
}
```

The client system hosting the masternode is configured with an iptables route as suggested by the documentation for a TOR style masternode (since this is marginally similar) as such (iptables output):
```
 pkts bytes target     prot opt in     out     source               destination         
    1    60 REDIRECT   tcp  --  any    any     anywhere             \<myip>       tcp dpt:17771 redir ports 17771
```

(Sorry it took so long, I was asked in slack over a month ago to post this issue, I wanted to see if the workaround I think I found really would work reliably...whilst not wanting to futz with the masternode I'm maintaining)

### Can you reliably reproduce the issue?
Yes.

#### If so, please list the steps to reproduce below:
0. Set up a client behind a traditional firewall where the firewall has a world routeable fixed IP and port map 17771 through the firewall to the client.
   a. also ensure that the iptables configuration on the client is set to redirect traffic coming from the client to the fixed IP is redirected local
1. ensure you have the masternode.conf, diamond.conf and account with 10k as required
2. ensure diamondd is running
3. execute diamond-cli masternode start-alias <alias>
   a. see that it returns 'success'
4. execute diamond-cli masternode status
   a. see that it doesn't return: Masternode successfully started

### Expected behavior
Tell us what should happen
The masternode should successfully start

### Actual behavior
Tell us what happens instead
The masternode is reported by "status" to be "not capable"

To workaround this what I do is start diamondd and the mn alias, which pretty quickly gives up as not capable, open 17771 on the client using nc -l 17771 and wait for a message to come in from another node.  When that happens, I restart diamondd and then right away I restart it again and then issue the masternode start-alias command.   For some reason this works and the masternode will start (I assume related to how this helps resolve the "checking inbound connection" failing issue....and there I'm assuming that's what is actually failing) - so far it's been a pretty reliable workaround for getting the masternode back up and going.

### What version of DMD Core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package.
$ dmd/diamond-cli --version
Diamond Core RPC client version v3.0.0.13-gcbcb549

### Machine specs:
- OS: Linux on a VM in virtualbox, plenty of memory and disk space, and the masternode does actually run very swimmingly I might add, once it's actually up.

### Any extra information that might be useful in the debugging process.
From the debug log, this is the relevant section:
```
2017-12-07 05:41:30 receive version message: /DMD Core:3.0.0.13/: version 70717, blocks=53409, us=\<myip>:59008, peer=14
2017-12-07 05:41:30 Added time data, samples 13, offset +0 (+0 minutes)
2017-12-07 05:41:30 nTimeOffset = +0  (+0 minutes)
2017-12-07 05:41:31 CMasternodeSync:ProcessMessage - ssc - got inventory count 10 0
2017-12-07 05:41:31 CMasternodeSync:ProcessMessage - ssc - got inventory count 11 0
2017-12-07 05:41:36 CMasternodeSync:ProcessMessage - ssc - got inventory count 10 0
2017-12-07 05:41:36 CMasternodeSync:ProcessMessage - ssc - got inventory count 11 0
2017-12-07 05:41:41 CMasternodeSync:ProcessMessage - ssc - got inventory count 10 0
2017-12-07 05:41:41 CMasternodeSync:ProcessMessage - ssc - got inventory count 11 0
2017-12-07 05:41:46 CMasternodeSync::GetNextAsset - Sync has finished
2017-12-07 05:41:46 CActiveMasternode::ManageStatus() - Checking inbound connection to '\<myip>:17771'
2017-12-07 05:41:46 CActiveMasternode::ManageStatus() - not capable: Could not connect to \<myip>:17771
```

I poked around at the code a bit here, but I didn't have enough time to drive this to any kind of root cause in the code because of the complexity of the networking code in place.  I'm happy to dig further and do more analysis (including capturing tcpdump-s on the participating jumps that I have direct access to and analyzing them or if you want to point me to a more specific place in the code base where this check is actually getting called and decided on.

**Comment by joshafest** [comment]
Your IP maybe wrong

**Comment by joshafest** [comment]
sometimes you restart your pc and this problem get fixed

**Comment by jerpat** [comment]
My IP isn't wrong it actually resolves to the proper DNS name of the address when I do an iptables --list
It fails to work in the expected manner no matter what I do....I've never had it work unless I follow the workaround.  And, that was very trial and error :)

**Comment by jerpat** [comment]
and....all the IP addresses are the same.....and, it wouldn't work at all if something in there was configured with the wrong IP address.

**Comment by jerpat** [comment]
I was able to resolve the problem.   I had a port map on my router that was fat fingered....sorry for the trouble...
