### ISSUE TITLE
gui available and total balance

### ISSUE THREAD

**Issue by cryptonit** [LIMXTEC/DMDv3#4]
in gui
there is no difference between useable balance and total balance

coins immature (from POS/Masternoder) are added to total and available

![image](https://user-images.githubusercontent.com/18220156/29528038-db78dae4-869a-11e7-95ce-92f6b6352f1d.png)

expected behavior:

available should be total - pending - immature

**Comment by joshafest** [comment]
FIXED: commit
https://github.com/LIMXTEC/DMDv3/commit/af0e7664181c865b9393cbcaab4aef44e5b476d4

**Comment by cryptonit** [comment]
we have user reports that total balance now become false over time
can it be that once POS blocks mature u add it again to total too?
it should be removed from available and then added again on available
but total should not be affected by POS non mature or mature change
